ADB_PRO/ADB_PRO/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',views.LoginView.as_view(),name='login'),
    path('accounts/logout/',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'}),

    path('',include('ChristKart.urls')),
]

ADB_PRO/ChristKart/urls.py
from django.urls import path
from ChristKart import views

app_name = 'ChristKart'

urlpatterns=[
path('',views.index.as_view(),name='home'),
path('plates',views.plates.as_view(),name='plates'),
path('straws',views.straws.as_view(),name='straws'),
path('bags',views.bags.as_view(),name='bags'),
path('register',views.registerView,name='register'),
path('user_login',views.user_login,name='user_login'),
path('user_logout',views.user_logout,name='user_logout'),

]

ADB_PRO/ChristKart/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Registration(models.Model):
    GENDER_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female'))

    user = models.OneToOneField(User,on_delete = models.CASCADE,null=True)
    
    gender = models.CharField(choices=GENDER_CHOICES, max_length=128,unique=False)
    age = models.PositiveIntegerField(unique=False)
    profession = models.CharField(max_length=256)
    location = models.CharField(max_length=600)

ADB_PRO/ChristKart/forms.py
from ChristKart.models import Registration
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = Registration
        fields = ('age','gender','profession','location')

ADB_PRO/ChristKart/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,TemplateView,CreateView,UpdateView,DeleteView,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

from ChristKart.models import Registration
from ChristKart.forms import UserForm,UserProfileForm
# Create your views here.


class index(TemplateView):
    template_name = 'index.html';
class plates(TemplateView):
    template_name = 'plates.html'

class bags(TemplateView):
    template_name = 'bags.html'
class straws(TemplateView):
    template_name = 'straws.html'



def registerView(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'register_form.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



########################################



def user_login(request):
    if request.method == 'POST':
        username =  request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('ChristKart:home'))
            else:
                return HttpResponse('Account not active')

        else:
            return HttpResponse("Invalid Login Credentials")
    else:
        return render(request,'user_login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('ChristKart:home'))

ADB_PRO/templates/bags.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
    <style>
      body{
        background-image: url("{% static 'back_02.jpg' %}");
        background-position: center;
 background-repeat: no-repeat;
 background-size: cover;

      }

    </style>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#" style="font-size:40px;">ChristKart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"  style="font-size:20px;">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Men's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Women's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#"  style="font-size:20px;"></a>
        </li>
      </ul>
    </div>
  </nav>





  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">

<img class="card-img-top" src="{% static 'redbag.jpg' %}" style="width:200px;" alt="Card image cap">
  <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
  <br>
  15.6 inch laptop bag ( plastic)



        </th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    <tr>
      <td></td>
      <td>1</td>
      <td>Rs. 5599/-</td>
      <td>N/A</td>
    </tr>

    </table>


    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">

  <img class="card-img-top" src="{% static 'superior.jpg' %}" style="width:200px;" alt="Card image cap">
    <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy

      </a>

    <br>
    15.6 inch superior quaity cloth bag




          </th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          <th scope="col">Rating</th>
        </tr>
      </thead>
      <tr>
        <td>  <div class="alert alert-primary" role="alert">
      Running out of stock
    </div></td>
        <td>1</td>
        <td>Rs. 5599/-</td>
        <td>N/A</td>
      </tr>

      </table>


      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">

    <img class="card-img-top" src="{% static 'faux.jpg' %}" style="width:200px;" alt="Card image cap">
      <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
      <br>
      15.6 inch Faux leather




            </th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Rating</th>
          </tr>
        </thead>
        <tr>
          <td></td>
          <td>1</td>
          <td>Rs. 250</td>
          <td>3 Stars</td>
        </tr>

        </table>

  </body>
</html>

ADB_PRO/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
    <style>
      body{
        background-image: url("{% static 'back_02.jpg' %}");
        background-position: center;
 background-repeat: no-repeat;
 background-size: cover;

      }

    </style>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'ChristKart:home' %}" style="font-size:40px;">ChristKart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"  style="font-size:20px;">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Men's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Women's Corner</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item" style="margin-left:300px;">
          <a class="nav-link" href="{% url 'ChristKart:user_logout' %}"  style="font-size:20px;">Logout</a>
        </li>

        <li class="nav-item" style="margin-top:0px;">

          <a class="nav-link" href="#"  style="font-size:20px;">User : {{user.username}}</a>
        </li>

        {% else %}
        <li class="nav-item" style="margin-left:300px;">
          <a class="nav-link" href="{% url 'ChristKart:user_login' %}"  style="font-size:20px;">Login</a>
        </li>

        <li class="nav-item" style="margin-left:20px;">
          <a class="nav-link" href="{% url 'ChristKart:register' %}"  style="font-size:20px;"> Register</a>
        </li>
        {% endif %}


      </ul>

    </div>





  </nav>













{% block content %}

{% endblock %}








  </body>
</html>

ADB_PRO/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">


<div class="jumbotron"
style="background:white;">
<img src="{% static 'mb_01.jpg' %}"style="margin-top:-50px; float:right;" alt="">
<h1 class="display-4">The Biggest Corona Sale is Here</h1>
<p class="lead"> With upto 50% off on electronics and flat 20% cash back on Furniture !!</p>
<hr class="my-4">
<p>Hurry up!</p>
<p class="lead">
<a class="btn btn-primary btn-lg" href="#" role="button">Buy Now</a>
</p>


<div class="container" >
<table class="table">
<thead>
  <tr>
    <th scope="col">
      <div class="card" style="width: 13rem;">
        <img class="card-img-top" src="{% static 'royalplates.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Plates</h5>
          <p class="card-text">Beautiful in design, as well as price</p>
          <a href="{% url 'ChristKart:plates' %}" class="btn btn-primary disabled">Explore </a>
        </div>
      </div></th>
    <th scope="col">
      <div class="card" style="width: 13rem;">
        <img class="card-img-top" src="{% static 'eco.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Straws</h5>
          <p class="card-text">High-Quality and Eco-Friendly</p>
          <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary">Explore</a>
        </div>
      </div>
    </th>
    <th scope="col">

      <div class="card" style="width: 13rem;">
        <img class="card-img-top"src="{% static 'redbag.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Bags</h5>
          <p class="card-text">Stronger and Longer</p>
          <a href="{% url 'ChristKart:bags' %}" class="btn btn-primary disabled">Explore</a>
        </div>
      </div>

    </th>

  </tr>
</thead>

</table>

</div>




</div>

</div>


{% endblock %}

ADB_PRO/templates/plates.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
    <style>
      body{
        background-image: url("{% static 'back_02.jpg' %}");
        background-position: center;
 background-repeat: no-repeat;
 background-size: cover;

      }

    </style>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#" style="font-size:40px;">ChristKart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"  style="font-size:20px;">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Men's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Women's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#"  style="font-size:20px;"></a>
        </li>
      </ul>
    </div>
  </nav>


  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">

<img class="card-img-top" src="{% static 'ecoplates.jpg' %}" style="width:200px;" alt="Card image cap">
  <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
  <br>
  Eco leaf plates (8 numbers)



        </th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Delivery</th>
      </tr>
    </thead>
    <tr>
      <td></td>
      <td>8</td>
      <td>Rs. 459/-</td>
      <td>Delivery in 3 days, if ordered before 12:00 hrs
</td>
    </tr>

    </table>


  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">

<img class="card-img-top" src="{% static 'royalplates.jpg' %}" style="width:200px;" alt="Card image cap">
  <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
  <br>
  Royal Plates( 8 numbers)



        </th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Delivery</th>
      </tr>
    </thead>
    <tr>
      <td></td>
      <td>8</td>
      <td>Rs. 459/-</td>
      <td>in 4 Days</td>
    </tr>

    </table>


    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">

  <img class="card-img-top" src="{% static 'stainless.jpg' %}" style="width:200px;" alt="Card image cap">
    <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
    <br>
    SS Stainless Stell plates (8 numbers)



          </th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          <th scope="col">Delivery</th>
        </tr>
      </thead>
      <tr>
        <td></td>
        <td>8</td>
        <td>Rs. 459/-</td>
        <td>in 4 Days</td>
      </tr>

      </table>




  </body>
</html>

ADB_PRO/templates/register_form.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<style media="screen">
  input{
    width:300px;
    height:30px;
    text-align: center;

  }
</style>


<div class="jumbotron">
<center>

  <div class="container">


    {% if registered == True %}
      <h1>Thanks for registering</h1>
    {% else %}
    <h1>Registration Form</h1>
    <br>



    <form class="" method="post">
      {% csrf_token %}

      {{user_form.as_p}}
    {{profile_form.as_p}}
  <input type="submit" name="" value="Login" class="btn btn-primary">

</form>








    {% endif %}






  </div>
  </center>

</div>


{% endblock %}

ADB_PRO/templates/straws.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
    <style>
      body{
        background-image: url("{% static 'back_02.jpg' %}");
        background-position: center;
 background-repeat: no-repeat;
 background-size: cover;

      }

    </style>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#" style="font-size:40px;">ChristKart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"  style="font-size:20px;">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Men's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"  style="font-size:20px;">Women's Corner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#"  style="font-size:20px;"></a>
        </li>
      </ul>
    </div>
  </nav>





  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">

<img class="card-img-top" src="{% static 'plasto.jpg' %}" style="width:200px;" alt="Card image cap">
  <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
  <br>
          Plasto straws for party


        </th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    <tr>
      <td></td>
      <td>100</td>
      <td>Rs. 250</td>
      <td>3.5 Stars</td>
    </tr>

    </table>


    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">

  <img class="card-img-top" src="{% static 'eco.jpg' %}" style="width:200px;" alt="Card image cap">
    <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
    <br>
    Eco Paper Drinking straw



          </th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          <th scope="col">Rating</th>
        </tr>
      </thead>
      <tr>
        <td></td>
        <td>100</td>
        <td>Rs. 250</td>
        <td>4.5 Stars</td>
      </tr>

      </table>


      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">

    <img class="card-img-top" src="{% static 'mini.jpg' %}" style="width:200px;" alt="Card image cap">
      <a href="{% url 'ChristKart:straws' %}" class="btn btn-primary" style="float:right; margin-top:80px;width:100px;">  Buy  </a>
      <br>
      Minimo Reusable stainless Steel Straw



            </th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Rating</th>
          </tr>
        </thead>
        <tr>
          <td></td>
          <td>100</td>
          <td>Rs. 250</td>
          <td>3 Stars</td>
        </tr>

        </table>

  </body>
</html>

ADB_PRO/templates/user_login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<style media="screen">
  input{
    width:300px;
    height:30px;
    text-align: center;

  }
</style>


<div class="jumbotron">
<center>

  <div class="container">


    <h1>User Login</h1>
    <br>



<form class="" action="{% url 'ChristKart:user_login' %}" method="post">
  {% csrf_token %}
<input type="text" name="username" placeholder="Enter username">
<input type="password" name="password" placeholder="Enter Password">

  <input type="submit" name="" value="Login" class="btn btn-primary">


</form>








  </div>
  </center>

</div>


{% endblock %}